

-- ----------------------------
-- Table structure for HWESightHosts
-- ----------------------------
DROP TABLE IF EXISTS "HW_ESIGHT_SERVER_CHILD_DN";
CREATE TABLE "HW_ESIGHT_SERVER_CHILD_DN" (
"ID"  integer PRIMARY KEY AUTO_INCREMENT NOT NULL,
"ESIGHT_HA_SERVER_ID"  int NOT NULL,
"DN"  nvarchar(255) NOT NULL,
"CREATE_TIME"  datetime NOT NULL,
CONSTRAINT UNIQUE_ESIGHT_HA_SERVER_ID_DN UNIQUE (ESIGHT_HA_SERVER_ID,DN),
FOREIGN KEY (ESIGHT_HA_SERVER_ID) REFERENCES HW_ESIGHT_HA_SERVER (ID) ON DELETE CASCADE
);
